"""Primera migración

Revision ID: ddcfab4316d3
Revises: 
Create Date: 2025-04-07 06:08:55.638335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddcfab4316d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono_cliente', sa.String(
            length=20), nullable=False, server_default='pendiente'))
        batch_op.add_column(sa.Column('tipo_asunto', sa.String(
            length=50), nullable=False, server_default='pendiente'))
        batch_op.add_column(sa.Column('abogado', sa.String(
            length=100), nullable=False, server_default='pendiente'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_column('abogado')
        batch_op.drop_column('tipo_asunto')
        batch_op.drop_column('telefono_cliente')

    # ### end Alembic commands ###
